controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ################################################for Joint state  
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # gripper_controller:
    #   type: forward_command_controller/ForwardCommandController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda_arm_controller:
  ros__parameters:
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      panda_joint1: { trajectory: 0.2, goal: 0.1 }
      panda_joint2: { trajectory: 0.2, goal: 0.1 }
      panda_joint3: { trajectory: 0.2, goal: 0.1 }
      panda_joint4: { trajectory: 0.2, goal: 0.1 }
      panda_joint5: { trajectory: 0.2, goal: 0.1 }
      panda_joint6: { trajectory: 0.2, goal: 0.1 }
      panda_joint7: { trajectory: 0.2, goal: 0.1 }
      #panda_finger_joint1: { trajectory: 0.2, goal: 0.1 }
      #panda_finger_joint2: { trajectory: 0.2, goal: 0.1 }

gripper_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    # interface_name: position
      
    ################################################for Joint state  
    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

      
